<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">

    <!-- Camera dimensions -->
    <xacro:property name="camera_length" value="0.01"/>
    <xacro:property name="camera_height" value="0.05"/>
    <xacro:property name="camera_width" value="0.1"/>

    <!-- Ensure base dimensions exist -->
    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_height" value="0.2"/>

    <!-- Camera link -->
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>        
        </collision>
        <xacro:box_inertia m="0.1" l="${camera_length}" w="${camera_width}" h="${camera_height}"
                            xyz="0 0 0"  rpy="0 0 0"/>
    </link>

    <!-- Joint to attach the camera to the base -->
    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link" />
        <origin xyz="${(base_length + camera_length)/2.0} 0 ${base_height / 2.0}" rpy="0 0 0"/>
    </joint>

    <!-- Ignition Gazebo camera plugin -->
    <gazebo reference="camera_link">
        <sensor name="camera_sensor" type="camera">
            <camera>
                <horizontal_fov>1.047</horizontal_fov> <!-- 60 degrees -->
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format> 
                </image>
                <clip>
                    <near>0.1</near>
                    <far>100</far>
                </clip>
            </camera>
            
            <!-- Noise should be here -->
            <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.007</stddev>
            </noise>

            <always_on>true</always_on>
            <update_rate>10</update_rate>
            <visualize>true</visualize>
            <topic>camera/image_raw</topic>

            <plugin filename="libgz-sim-sensor-system.so" name="gz::sim::systems::Camera">
                <ros>
                    <namespace>/</namespace>
                    <remapping>camera/image_raw:=camera/image_raw</remapping>
                </ros>
            </plugin>
        </sensor>
    </gazebo>
</robot>
